### ISSUE TITLE
Segfaults with simple normal use but not when querying individual tracks

### ISSUE THREAD

**Issue by tuomosipola** [thierer/lsdvd#3]
Disney DVD with apparent copy protection scheme. Plays fine with VLC or mpv but lsdvd doesn't work with it. 

Segfaults when using the normal way:

> $ lsdvd
> libdvdread: Unable to read invalid PCG
> libdvdread: PTT search table too small.
> libdvdread: PTT search table too small.
> libdvdread: Invalid IFO for title 36 (VTS_36_0.BUP).
> libdvdread: PTT search table too small.
> libdvdread: PTT search table too small.
> libdvdread: Invalid IFO for title 37 (VTS_37_0.BUP).
> libdvdread: PTT search table too small.
> libdvdread: PTT search table too small.
> libdvdread: Invalid IFO for title 38 (VTS_38_0.BUP).
> Segmentation fault (core dumped)

But works when I run it for the individual tracks, though prints the unnecessary warnings, e.g., first one:

> $ lsdvd -t 1
> libdvdread: Unable to read invalid PCG
> libdvdread: PTT search table too small.
> libdvdread: PTT search table too small.
> libdvdread: Invalid IFO for title 36 (VTS_36_0.BUP).
> libdvdread: PTT search table too small.
> libdvdread: PTT search table too small.
> libdvdread: Invalid IFO for title 37 (VTS_37_0.BUP).
> libdvdread: PTT search table too small.
> libdvdread: PTT search table too small.
> libdvdread: Invalid IFO for title 38 (VTS_38_0.BUP).
> Disc Title: Pirates_Of_The_Carribean_4_GBR
> Disc Alternative Title: unknown
> Disc Serial Number: UNDEFINE
> libdvdread Disc-ID: 2e5958d7ed1729eddd33418a1d5718bf
> Title: 01, Length: 00:00:11.000 Chapters: 01, Cells: 01, Audio streams: 01, Subpictures: 00

**Comment by thierer** [comment]
Yeah, that's a constant problem with some dvds that have invalid structures. The reason why you don't get the segfault when you select a specific title is that then lsdvd only processes *that* title and doesn't run into the invalid ones. The warnings are from libdvdread, not lsdvd.

I've just pushed 6e3484bd39c6b5f42eb615c9f026288cea74597e that adds a few more sanity checks. Could you check if that solves your segfault?

**Comment by tuomosipola** [comment]
Many thanks! The new version still shows the libdvdread errors but does not segfault and shows all the confusing 99 tracks (only two of them shown below). 

> lsdvd-0.16$ ./lsdvd 
> libdvdread: Unable to read invalid PCG
> libdvdread: PTT search table too small.
> libdvdread: PTT search table too small.
> libdvdread: Invalid IFO for title 36 (VTS_36_0.BUP).
> libdvdread: PTT search table too small.
> libdvdread: PTT search table too small.
> libdvdread: Invalid IFO for title 37 (VTS_37_0.BUP).
> libdvdread: PTT search table too small.
> libdvdread: PTT search table too small.
> libdvdread: Invalid IFO for title 38 (VTS_38_0.BUP).
> Disc Title: Pirates_Of_The_Carribean_4_GBR
> Disc Alternative Title: unknown
> Disc Serial Number: UNDEFINE
> libdvdread Disc-ID: 2e5958d7ed1729eddd33418a1d5718bf
> Title: 01, Length: 00:00:11.000 Chapters: 01, Cells: 01, Audio streams: 01, Subpictures: 00
> 
> Title: 02, Length: 00:00:11.800 Chapters: 02, Cells: 03, Audio streams: 00, Subpictures: 00
> 
> ...

I still need to use VLC menu navigation to get the correct track number (33 here) for playing it with mpv, but I think it's impossible for lsdvd or libdvdread to detect it.

**Comment by thierer** [comment]
Glad to hear that it worked!
